In [393]:
import pandas as pd
import numpy as np

In [394]:
oc = pd.read_csv("MW-FO-nifty_bank_opt-19-Oct-2026.csv")
oc.describe()

,INSTRUMENT TYPE \n,SYMBOL \n,EXPIRY DATE \n,OPTION TYPE \n,STRIKE PRICE \n,LTP \n,CHANGE \n,%CHANGE \n,OPEN \n,HIGH \n,LOW \n,VOLUME \n(Contracts),VALUE \n (₹ Crores),OPEN INTEREST \n,UNDERLYING VALUE \n
count,907,907,907,907,907,907,907,907,907,907,907,907,907,907,907
unique,1,1,6,2,160,465,452,472,475,474,469,325,197,408,1
top,Index Options,BANKNIFTY,27-Oct-2026,Put,"57,000.00",-,-,-,-,-,-,-,-,-,"55,488.10"
freq,907,907,314,455,10,420,423,423,420,420,420,420,476,272,907

In [395]:
oc.columns = ['INSTRUMENT TYPE', 'SYMBOL', 'EXPIRY DATE', 'OPTION TYPE',
       'STRIKE PRICE', 'LTP', 'CHANGE', '%CHANGE', 'OPEN',
       'HIGH', 'LOW', 'VOLUME', 'VALUE',
       'OPEN INTEREST', 'UNDERLYING VALUE']
oc

,INSTRUMENT TYPE,SYMBOL,EXPIRY DATE,OPTION TYPE,STRIKE PRICE,LTP,CHANGE,%CHANGE,OPEN,HIGH,LOW,VOLUME,VALUE,OPEN INTEREST,UNDERLYING VALUE
0,Index Options,BANKNIFTY,27-Oct-2026,Put,"55,500.00",441.00,76.05,20.84,306.15,504.00,306.05,"2,01,020",250.98,"35,859","55,488.10"
1,Index Options,BANKNIFTY,27-Oct-2026,Call,"56,000.00",263.10,-214.40,-44.90,493.25,504.65,239.55,"1,63,321",162.72,"49,552","55,488.10"
2,Index Options,BANKNIFTY,27-Oct-2026,Call,"55,500.00",485.00,-282.25,-36.79,766.60,799.95,461.55,"1,60,758",272.57,"34,588","55,488.10"
3,Index Options,BANKNIFTY,27-Oct-2026,Put,"55,600.00",485.95,86.05,21.52,379.90,550.00,345.65,"1,08,186",147.16,"5,146","55,488.10"
4,Index Options,BANKNIFTY,27-Oct-2026,Call,"55,600.00",434.15,-268.35,-38.20,722.20,733.60,411.00,"1,08,009",167.03,"8,548","55,488.10"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
902,Index Options,BANKNIFTY,23-Nov-2026,Call,"58,700.00",-,-,-,-,-,-,-,-,-,"55,488.10"
903,Index Options,BANKNIFTY,23-Nov-2026,Put,"59,800.00",-,-,-,-,-,-,-,-,-,"55,488.10"
904,Index Options,BANKNIFTY,23-Nov-2026,Put,"60,100.00",-,-,-,-,-,-,-,-,-,"55,488.10"
905,Index Options,BANKNIFTY,23-Nov-2026,Call,"60,300.00",-,-,-,-,-,-,-,-,-,"55,488.10"
906,Index Options,BANKNIFTY,23-Nov-2026,Put,"60,900.00",-,-,-,-,-,-,-,-,-,"55,488.10"

In [396]:
oc = oc.drop(["INSTRUMENT TYPE", "SYMBOL", "CHANGE", "%CHANGE", "OPEN", "HIGH", "LOW", "VOLUME", "VALUE", "OPEN INTEREST"], axis = 1)
oc

     EXPIRY DATE OPTION TYPE STRIKE PRICE     LTP UNDERLYING VALUE
0    27-Oct-2026         Put    55,500.00  441.00        55,488.10
1    27-Oct-2026        Call    56,000.00  263.10        55,488.10
2    27-Oct-2026        Call    55,500.00  485.00        55,488.10
3    27-Oct-2026         Put    55,600.00  485.95        55,488.10
4    27-Oct-2026        Call    55,600.00  434.15        55,488.10
..           ...         ...          ...     ...              ...
902  23-Nov-2026        Call    58,700.00       -        55,488.10
903  23-Nov-2026         Put    59,800.00       -        55,488.10
904  23-Nov-2026         Put    60,100.00       -        55,488.10
905  23-Nov-2026        Call    60,300.00       -        55,488.10
906  23-Nov-2026         Put    60,900.00       -        55,488.10

[907 rows x 5 columns]

In [397]:
oc.describe()

        EXPIRY DATE OPTION TYPE STRIKE PRICE  LTP UNDERLYING VALUE
count           907         907          907  907              907
unique            6           2          160  465                1
top     27-Oct-2026         Put    57,000.00    -        55,488.10
freq            314         455           10  420              907

In [398]:
oc.info()

<class 'pandas.DataFrame'>
RangeIndex: 907 entries, 0 to 906
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   EXPIRY DATE       907 non-null    str
 1   OPTION TYPE       907 non-null    str
 2   STRIKE PRICE      907 non-null    str
 3   LTP               907 non-null    str
 4   UNDERLYING VALUE  907 non-null    str
dtypes: str(5)
memory usage: 35.6 KB

In [399]:
oc

     EXPIRY DATE OPTION TYPE STRIKE PRICE     LTP UNDERLYING VALUE
0    27-Oct-2026         Put    55,500.00  441.00        55,488.10
1    27-Oct-2026        Call    56,000.00  263.10        55,488.10
2    27-Oct-2026        Call    55,500.00  485.00        55,488.10
3    27-Oct-2026         Put    55,600.00  485.95        55,488.10
4    27-Oct-2026        Call    55,600.00  434.15        55,488.10
..           ...         ...          ...     ...              ...
902  23-Nov-2026        Call    58,700.00       -        55,488.10
903  23-Nov-2026         Put    59,800.00       -        55,488.10
904  23-Nov-2026         Put    60,100.00       -        55,488.10
905  23-Nov-2026        Call    60,300.00       -        55,488.10
906  23-Nov-2026         Put    60,900.00       -        55,488.10

[907 rows x 5 columns]

In [400]:
exp = oc["EXPIRY DATE"].unique()
for i in range(len(exp)):
    print(exp[i])
arr = []
arr

27-Oct-2026
23-Nov-2026
29-Dec-2026
30-Mar-2027
29-Jun-2027
28-Sep-2027

[]

In [401]:
arr= []
for i in range(len(exp)):
    arr.append(pd.read_csv(f"option-chain-ED-BANKNIFTY-{exp[i]}.csv", header = 1))

In [402]:
count = 0
for i in range(len(arr)):
    arr[i] = arr[i].drop(["NO TEXT", "NO TEXT.1"], axis = 1)
    count += len(arr[i])
print(arr[1])

      OI CHNG IN OI VOLUME     IV    LTP   CHNG BID QTY       BID       ASK  \
0      1          -      -      -      -      -      30  8,392.15  9,135.65
1      -          -      -      -      -      -      30  7,904.30  8,675.50
2     16          -      -      -      -      -      60  7,726.95  7,995.85
3      1          -      -      -      -      -      30  6,965.25  7,674.00
4     14          -      -      -      -      -      30  6,488.90  7,120.65
..   ...        ...    ...    ...    ...    ...     ...       ...       ...
144   26         -5     23  17.32  10.45  -2.20      90      9.50     10.45
145  195         -1     13  17.99   9.25  -3.45     120      9.00     10.15
146   72          5      7  19.08  10.00  -2.00      30      8.50      9.95
147  536         28    112  18.99   6.45  -3.05     900      6.55      8.95
148   35          -      -  19.04      -      -      90      5.55      8.90

    ASK QTY  ... BID QTY.1     BID.1      ASK.1 ASK QTY.1    CHNG.1     LTP.1  \
0        30  ...       360     17.45      18.85       120     -4.60     19.00
1        30  ...       150     18.05          -         -         -         -
2        30  ...       390     22.00      23.45        60     -4.15     23.00
3        30  ...        60     24.25      30.75        30     -3.50     27.80
4        30  ...        60     28.55      35.90        30      0.30     35.45
..      ...  ...       ...       ...        ...       ...       ...       ...
144      60  ...        30  7,275.65   8,399.15     1,410         -         -
145      90  ...        30  7,927.10   8,916.50     1,410   -400.00  7,900.00
146      90  ...        30  8,240.50   9,705.60     1,410  1,811.70  8,350.00
147     300  ...        30  8,908.95   9,050.25       180    402.10  9,023.35
148     180  ...        30  9,107.20  11,030.35     1,410         -         -

      IV.1 VOLUME.1 CHNG IN OI.1 OI.1
0    25.63      219          107  307
1        -        -            -    -
2    23.56      258          -15  376
3    22.83      111           -4   57
4    22.27      157           38  422
..     ...      ...          ...  ...
144  21.82        -            -   73
145      -        2            2    8
146      -        1            1    1
147  30.13       36           30  124
148  36.23        -            -    5

[149 rows x 21 columns]

In [403]:
print(((arr[1].columns)))

Index(['OI', 'CHNG IN OI', 'VOLUME', 'IV', 'LTP', 'CHNG', 'BID QTY', 'BID',
       'ASK', 'ASK QTY', 'STRIKE', 'BID QTY.1', 'BID.1', 'ASK.1', 'ASK QTY.1',
       'CHNG.1', 'LTP.1', 'IV.1', 'VOLUME.1', 'CHNG IN OI.1', 'OI.1'],
      dtype='str')

In [404]:
for i in range(len(arr)):
    df1 = arr[i][['OI', 'CHNG IN OI', 'VOLUME', 'IV', 'LTP', 'CHNG', 'BID QTY', 'BID', 'ASK', 'ASK QTY', 'STRIKE']]
    df2 = arr[i][['OI.1', 'CHNG IN OI.1', 'VOLUME.1', 'IV.1', 'LTP.1', 'CHNG.1', 'BID QTY.1', 'BID.1', 'ASK.1', 'ASK QTY.1', 'STRIKE']]
    df2.columns = ['OI', 'CHNG IN OI', 'VOLUME', 'IV', 'LTP', 'CHNG', 'BID QTY', 'BID', 'ASK', 'ASK QTY', 'STRIKE']
    df1.loc[ : , "OPTION TYPE"]= "Call"
    df2.loc[ : , "OPTION TYPE"]= "Put"
    arr[i]= pd.concat([df1, df2], ignore_index=True)
    for j in range(len(arr[i])):
        arr[i].loc[j, "EXPIRY DATE"] = exp[i]

In [405]:
oca = pd.DataFrame()
for i in range(len(arr)):
    df = pd.concat([oca, arr[i]], ignore_index = True)
    oca = df

oca["EXPIRY DATE"].unique()

<StringArray>
['27-Oct-2026', '23-Nov-2026', '29-Dec-2026', '30-Mar-2027', '29-Jun-2027',
 '28-Sep-2027']
Length: 6, dtype: str

In [406]:
oca.columns

Index(['OI', 'CHNG IN OI', 'VOLUME', 'IV', 'LTP', 'CHNG', 'BID QTY', 'BID',
       'ASK', 'ASK QTY', 'STRIKE', 'OPTION TYPE', 'EXPIRY DATE'],
      dtype='str')

In [407]:
oca = oca[["IV", "LTP", "STRIKE", "OPTION TYPE", "EXPIRY DATE"]]
oca

        IV       LTP     STRIKE OPTION TYPE  EXPIRY DATE
0        -  8,535.00  47,000.00        Call  27-Oct-2026
1        -         -  47,500.00        Call  27-Oct-2026
2        -  7,578.85  48,000.00        Call  27-Oct-2026
3        -  7,085.00  48,500.00        Call  27-Oct-2026
4    47.87  6,650.00  49,000.00        Call  27-Oct-2026
..     ...       ...        ...         ...          ...
929      -         -  51,000.00        Call  28-Sep-2027
930      -         -  63,000.00        Call  28-Sep-2027
931      -         -  48,000.00         Put  28-Sep-2027
932      -         -  51,000.00         Put  28-Sep-2027
933      -         -  63,000.00         Put  28-Sep-2027

[934 rows x 5 columns]

In [408]:
oc.rename(columns = {"STRIKE PRICE": "STRIKE"}, inplace = True)
oc

     EXPIRY DATE OPTION TYPE     STRIKE     LTP UNDERLYING VALUE
0    27-Oct-2026         Put  55,500.00  441.00        55,488.10
1    27-Oct-2026        Call  56,000.00  263.10        55,488.10
2    27-Oct-2026        Call  55,500.00  485.00        55,488.10
3    27-Oct-2026         Put  55,600.00  485.95        55,488.10
4    27-Oct-2026        Call  55,600.00  434.15        55,488.10
..           ...         ...        ...     ...              ...
902  23-Nov-2026        Call  58,700.00       -        55,488.10
903  23-Nov-2026         Put  59,800.00       -        55,488.10
904  23-Nov-2026         Put  60,100.00       -        55,488.10
905  23-Nov-2026        Call  60,300.00       -        55,488.10
906  23-Nov-2026         Put  60,900.00       -        55,488.10

[907 rows x 5 columns]

In [438]:
for i in oc.index:
    for j in oca.index:
        if((oc.loc[i, "EXPIRY DATE"] == oca.loc[j, "EXPIRY DATE"]) & (oc.loc[i, "OPTION TYPE"] == oca.loc[j, "OPTION TYPE"]) & (oc.loc[i, "STRIKE"] == oca.loc[j, "STRIKE"])):
            oc.loc[i, "IV"] = oca.loc[j, "IV"]
            break

In [439]:
oc = oc.replace('-', np.nan)

In [440]:
oc

     EXPIRY DATE OPTION TYPE     STRIKE     LTP UNDERLYING VALUE     IV
0    27-Oct-2026         Put  55,500.00  441.00        55,488.10  15.08
1    27-Oct-2026        Call  56,000.00  263.10        55,488.10  13.08
2    27-Oct-2026        Call  55,500.00  485.00        55,488.10  13.07
3    27-Oct-2026         Put  55,600.00  485.95        55,488.10  14.98
4    27-Oct-2026        Call  55,600.00  434.15        55,488.10  13.10
..           ...         ...        ...     ...              ...    ...
902  23-Nov-2026        Call  58,700.00     NaN        55,488.10    NaN
903  23-Nov-2026         Put  59,800.00     NaN        55,488.10    NaN
904  23-Nov-2026         Put  60,100.00     NaN        55,488.10    NaN
905  23-Nov-2026        Call  60,300.00     NaN        55,488.10    NaN
906  23-Nov-2026         Put  60,900.00     NaN        55,488.10    NaN

[907 rows x 6 columns]